INSERT INTO TECNICO (NOME, NICK, SOBRENOME, VALOR, PAIS_ID, FOTO) VALUES
('Erick', 'Erickão', 'Cardoso', 6, 28, 'foto.jpg'),
('Gabriel', 'MiT', 'Souza', 6, 28, 'foto.jpg'),
('Lucas', 'Maestro', 'Pierre', 6, 28, 'foto.jpg'),
('Gabriel', 'Hailer', 'Negreiros', 6, 28, 'foto.jpg'),
('César', 'juc', 'Barbosa', 6, 28, 'foto.jpg'),
('Vinícius', 'Neki', 'Ghilardi', 6, 28, 'foto.jpg'),
('Otavio', 'Skullz', 'Macedo', 6, 28, 'foto.jpg'),
('Renan', 'Dezenove', 'Crespo', 6, 28, 'foto.jpg'),
('Alexander', 'Abaxial', 'Haibel', 6, 60, 'foto.jpg'),
('Gabriel', 'Von', 'Barbosa', 6, 28, 'foto.jpg'),
('Luis', 'Piroxz', 'Chavez', 6, 28, 'foto.jpg'),
('Ram', 'Brokenshard', 'Djemal', 6, 90, 'foto.jpg'),
('Hugo', 'Galfi', 'Garcia', 6, 28, 'foto.jpg'),
('João P.', 'Dionrray', 'Barbosa', 6, 28, 'foto.jpg'),
('', 'Leandro Martins', '', 6, 28, 'foto.jpg'),
('John', 'Rnglol', 'Crichton', 6, 35, 'foto.jpg'),
('Arthur', 'PAADA', 'Zarzur', 6, 28, 'foto.jpg'),
('Sylvio', 'FeeFoo', 'Júnior', 6, 28, 'foto.jpg'),
('', 'Cowelhy', '', 6, 28, 'foto.jpg'),
('', 'Nuddle', '', 6, 28, 'foto.jpg'),
('', 'CptJack', '', 6, 28, 'foto.jpg'),
('', 'Peter Dun', '', 6, 145, 'foto.jpg'),
('Thiago', 'Djokovic', 'Maia', 6, 28, 'foto.jpg'),
('Alexandre', 'DrPuppet', 'Weber', 6, 28, 'foto.jpg'),
('Luca', 'Gratis150ml', 'Baptistella', 6, 28, 'foto.jpg'),
('Lee', 'Icarus', 'In-Cheol', 6, 46, 'foto.jpg'),
('Daniel', 'Danagorn', 'Drummond', 6, 28, 'foto.jpg');